In [1]:
import numpy as np #넘파이 로딩

#sqrt() 제곱근을 구하는 함수
print(np.sqrt(100))
print(np.sqrt(16))
print(np.sqrt(7))
# nan : not anumber 유효한 값이 아닌
# na : not available
# None : 리턴값이 없거나 유효한 값이 없을 때, 결측값
print(np.sqrt(-4))

10.0
4.0
2.6457513110645907
nan


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in sqrt
  


In [4]:
a=[1,2,3]
b=[2,4,6]

print(a+b)
#print(a*b) 에러 발생
print(a*3)

[1, 2, 3, 2, 4, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [7]:
print(type(a)) #리스트
print(type(np.array(a))) #리스트를 넘파이 배열로 전환
a1=np.array(a)
print(a1)
print(a1[0]) #사용법은 리스트와 비슷함
print(a1[1])
print(a1[2])
a2=list(a1) #넘파이 배열을 리스트로 변환
print(a2)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
1
2
3
[1, 2, 3]


In [5]:
print(np.multiply(a,b))
print(np.array(a)+np.array(b))
print(np.array(a)*np.array(b))
print(np.array(a)-np.array(b))
print(np.array(a)/np.array(b))

[ 2  8 18]
[3 6 9]
[ 2  8 18]
[-1 -2 -3]
[0.5 0.5 0.5]


In [9]:
a=[-5,8,9,20,50,100,-500]
print(np.max(a)) #최대값(넘파이 함수)
print(np.min(a)) #최소값(넘파이 함수)
print(max(a)) #최대값(기본합수)
print(np.average(a)) #평균값
print(np.argmax(a)) #최대값의 인덱스
print(np.argmin(a)) #최소값의 인덱스

100
-500
100
-45.42857142857143
5
6


In [21]:
#넘파이의 랜덤 함수
import numpy as np
#랜덤 시드 설정(랜덤의 기준값)
#np.random.seed(100) #랜덤시드가 같으면 항상 같은 결과가 출력됨
np.random.randint(9) #0~9 미만의 랜던값

0

In [22]:
#100~150미만의 정수난수 5개 생성
a=np.random.randint(100,150,size=5)
print(a)

[110 130 134 102 134]


In [23]:
def make_numbers():
    numbers=[]
    for i in range(10):
        num = np.random.randint(1,100)
        if num not in numbers:
            numbers.append(num)
    return numbers

make_numbers()

[15, 35, 25, 16, 61, 59, 17, 10, 94, 87]

In [28]:
def make_numbers(a):
    numbers=[]
    while len(numbers)<a:
        num = np.random.randint(1,10)
        if num not in numbers:
            numbers.append(num)
    return numbers
#5개의 정수 난수
make_numbers(5)

[3, 5, 2, 6, 4]