In [4]:
import numpy as np

items = range(10,51,10) #10~50, step 10
print(list(items))
arr = np.array(items) #리스트를 넘파이배열로 변환
print(arr)
print(type(arr))
print(arr.shape) #데이터의 차원

[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)


In [6]:
items2=[list(range(1,6)), list(range(10,51,10))]
print(items2)
arr2=np.array(items2)
print(arr2)
print(arr2.shape) #2행 5열의 2차원 넘파이 배열

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
(2, 5)


In [7]:
#넘파이 배열의 연산
ar1 = np.array([[70,80],[195,185]]) #기본리스트로 할 경우 에러가 남
ar2 = np.array([[50,60],[70,80]]) #ar1과 ar2의 자리수가 다를경우 에러가 남
print(ar1+ar2) #각 자리수별로 연산 처리
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2) #실수몫
print(ar1//ar2) #정수몫

[[120 140]
 [265 265]]
[[ 20  20]
 [125 105]]
[[ 3500  4800]
 [13650 14800]]
[[1.4        1.33333333]
 [2.78571429 2.3125    ]]
[[1 1]
 [2 2]]


In [8]:
student1=[60,70,80]
student2=[77,88,99]
points=np.array([student1,student2])
print(points)
print(points.shape) #2행 3열의 넘파이 2차원 배열

[[60 70 80]
 [77 88 99]]


In [10]:
print(points.sum()) #전체 합계
print(points.sum(axis=0)) #열의 합계
print(points.sum(axis=1)) #행의 합계
print(points.mean()) #전체 평균
print(points.mean(axis=0))
print(points.mean(axis=1))


474
[137 158 179]
[210 264]
79.0
[68.5 79.  89.5]
[70. 88.]


In [13]:
import numpy as np
arr=np.array([20,10,-10,70,900,100])
print(arr)
arr2=np.sort(arr)
print(arr2) #오름차순 정렬
# start:stop:step
print(np.sort(arr[::-1])) #내림차순 정렬

[ 20  10 -10  70 900 100]
[-10  10  20  70 100 900]
[-10  10  20  70 100 900]


In [17]:
names=np.array(['김철수','이승호','김철수','김철수','홍상현','이영희','윤동주'])
ages=np.array([20,35,30,33,28,29,30,31,30,40,46])
print(names)
print(ages)
print(np.unique(names)) #중복값을 제거하는 함수
print(np.unique(ages))

['김철수' '이승호' '김철수' '김철수' '홍상현' '이영희' '윤동주']
[20 35 30 33 28 29 30 31 30 40 46]
['김철수' '윤동주' '이승호' '이영희' '홍상현']
[20 28 29 30 31 33 35 40 46]


In [23]:
import pandas as pd

sr=pd.Series(range(5,51,10))
print(sr)
# index 행인덱스에 사용할 이름들
sr=pd.Series(range(5,51,10),index=['a','b','c','d','e'])
print(sr)
print(sr['a']) #인덱스가 a인 값
sr['a']=500 #값을 변경
print(sr)

0     5
1    15
2    25
3    35
4    45
dtype: int64
a     5
b    15
c    25
d    35
e    45
dtype: int64
5
a    500
b     15
c     25
d     35
e     45
dtype: int64


In [24]:
#딕셔너리를 시리즈로 변환 key=>index, value=>data
emp={'김철수':5000,'김철호':7000,'한상민':4000,'문대용':4500}
sr=pd.Series(emp)
print(sr)


김철수    5000
김철호    7000
한상민    4000
문대용    4500
dtype: int64


In [26]:
#데이터프레임
a=pd.DataFrame({
    'name':['김철수','김대희','송영민','이희연','정미숙'],
    'weight':[80,70.4,65.5,45.9,51.2],
    'height':[170,180,155,143,154],
    'gender':['m','m','m','f','f']
})
print(a)
print(a.values) #값들
print(a.columns) #컬럼들
print(a.describe()) #기초 통계량
print(a['weight']) #컬럼1개 선택
print(a[['weight','height']]) #컬럼 여러개 선택
print(a[a.height>= 170]) #조건에 맞는 행
print(a[a.gender == 'm'])
print(a.sort_values(by='height')) #오름차순
print(a.sort_values(by='weight',ascending=False)) #내림차순

  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
2  송영민    65.5     155      m
3  이희연    45.9     143      f
4  정미숙    51.2     154      f
[['김철수' 80.0 170 'm']
 ['김대희' 70.4 180 'm']
 ['송영민' 65.5 155 'm']
 ['이희연' 45.9 143 'f']
 ['정미숙' 51.2 154 'f']]
Index(['name', 'weight', 'height', 'gender'], dtype='object')
          weight      height
count   5.000000    5.000000
mean   62.600000  160.400000
std    13.971936   14.570518
min    45.900000  143.000000
25%    51.200000  154.000000
50%    65.500000  155.000000
75%    70.400000  170.000000
max    80.000000  180.000000
0    80.0
1    70.4
2    65.5
3    45.9
4    51.2
Name: weight, dtype: float64
   weight  height
0    80.0     170
1    70.4     180
2    65.5     155
3    45.9     143
4    51.2     154
  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
2  송영민    65.5     