### 퍼셉트론

In [ ]:
#단층 퍼셉트론
import numpy as np
#단층 퍼셉트론(다수의 신호를 입력받아 하나의 신호를 출력)
def AND(x1,x2):
    x=np.array([x1,x2]) #입력값
    w=np.array([0.5,0.5]) #가중치(기울기)
    b=-0.7 #절편(편향)
    tmp=np.sum(w*x) + b # x에 가중치를 곱하고 편향을 더한 y값
    #print(tmp)
    if tmp <=0:
        return 0
    else:
        return 1
    
for xs in [(0,0),(1,0),(0,1),(1,1)]:
    y=AND(xs[0],xs[1])
    print(str(xs)+'->'+str(y))

In [ ]:
#NAND(AND의 역산)
def NAND(x1,x2):
    x=np.array([x1,x2]) #입력값
    w=np.array([-0.5,-0.5]) #가중치(기울기)
    b=0.7 #절편(편향)
    tmp=np.sum(w*x) + b # x에 가중치를 곱하고 편향을 더한 y값
    #print(tmp)
    if tmp <=0:
        return 0
    else:
        return 1
    
for xs in [(0,0),(1,0),(0,1),(1,1)]:
    y=NAND(xs[0],xs[1])
    print(str(xs)+'->'+str(y))

In [ ]:
#OR
def OR(x1,x2):
    x=np.array([x1,x2]) #입력값
    w=np.array([0.5,0.5]) #가중치(기울기)
    b=-0.2 #절편(편향)
    tmp=np.sum(w*x) + b # x에 가중치를 곱하고 편향을 더한 y값
    #print(tmp)
    if tmp <=0:
        return 0
    else:
        return 1
    
for xs in [(0,0),(1,0),(0,1),(1,1)]:
    y=OR(xs[0],xs[1])
    print(str(xs)+'->'+str(y))

In [ ]:
#다층 퍼셉트론
#단층 퍼셉트론으로는 xor 무제를 풀 수 없음
def XOR(x1,x2):
    s1=NAND(x1,x2)
    s2=OR(x1,x2)
    y=AND(s1,s2) #NAND와 OR를 조합
    return y

for xs in [(0,0),(1,0),(0,1),(1,1)]:
    y=XOR(xs[0],xs[1])
    print(str(xs)+'->'+str(y))

### 활성화 함수

In [ ]:
#계단함수
#활성화함수: 입력값의 총합을 출력값으로 변환하는 함수
#계단함수(y가 0보다 크면 1, 작으면 0으로 출력하는 활성화 함수)
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

def step_function(x):
    return np.array(x>0,dtype=np.int) #dtype 데이터 타입

X=np.arange(-5.0,5.0,0.1) #-5~5까지 0.1 간격으로 100개 생성

y=step_function(X)
print(len(X),X,y)
plt.plot(X,y)
plt.ylim(-0.1,1.1) #y축의 범위 지정
plt.show()

In [ ]:
np.e #오일러 상수

In [ ]:
# 1원을 1년 저축
#  => 원금 1원, 이자 1원
# 6개월씩 저축하면 1+0.5
#                 1원 이자0.5
#                 0.5원 이자 0.25 =>2.25원


In [7]:
#시그모이드 함수(S자 형태, 0.0~1.0 사이의 출력값)
import numpy as np
import matplotlib.pylab as plt

def sigmoid(x):
    return 1/(1+np.exp(-x))

X=np.arange(-5,5,0.1)
y=sigmoid(X)
plt.plot(X,y)
plt.ylim(-0.1,1.1)
plt.show()
print(X,y)

<Figure size 640x480 with 1 Axes>

[-5.00000000e+00 -4.90000000e+00 -4.80000000e+00 -4.70000000e+00
 -4.60000000e+00 -4.50000000e+00 -4.40000000e+00 -4.30000000e+00
 -4.20000000e+00 -4.10000000e+00 -4.00000000e+00 -3.90000000e+00
 -3.80000000e+00 -3.70000000e+00 -3.60000000e+00 -3.50000000e+00
 -3.40000000e+00 -3.30000000e+00 -3.20000000e+00 -3.10000000e+00
 -3.00000000e+00 -2.90000000e+00 -2.80000000e+00 -2.70000000e+00
 -2.60000000e+00 -2.50000000e+00 -2.40000000e+00 -2.30000000e+00
 -2.20000000e+00 -2.10000000e+00 -2.00000000e+00 -1.90000000e+00
 -1.80000000e+00 -1.70000000e+00 -1.60000000e+00 -1.50000000e+00
 -1.40000000e+00 -1.30000000e+00 -1.20000000e+00 -1.10000000e+00
 -1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -1.77635684e-14  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01
  1.00000000e+00  1.10000

In [ ]:
#ReLU(Rectified Linear Unit)
#입력값이 0보다 크면 그대로 출력, 0 이하면 0
def relu(x):
    return np.maximum(0,x) #가장 큰 값 리턴
x= np.arange(-5.0,5.0,0.1)
y=relu(x)
plt.plot(x,y)
plt.ylim(-1.0,5.5)
plt.show()
print(x,y)

In [2]:
#행렬의 곱셈
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(a.shape) #2행 2열의 행렬
b=np.array([[5,6],[7,8]])
print(b)
print(b.shape)
print(np.dot(a,b)) #행렬의 곱셈

[[1 2]
 [3 4]]
(2, 2)
[[5 6]
 [7 8]]
(2, 2)
[[19 22]
 [43 50]]


In [4]:
#행렬의 곱셈
a=np.array([[1,2,3],[4,5,6]])
print(a.shape) #2행 2열의 행렬
b=np.array([[1,2],[3,4],[5,6]]) #3행 2열의 행렬
print(b.shape)
print(np.dot(a,b)) #행렬의 곱셈 2행 3열 x3행2열

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [5]:
c=np.array([[1,2],[3,4]])
np.dot(a,c) #에러가 발생함 2행3열 x 2행2열

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
x=np.array([1,0.5]) #입력값
#첫번째 은닉층
w1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])#가중치
b1=np.array([[0.1,0.2,0.3]]) #편향(절편)
a1=np.dot(x,w1) + b1 #첫번째 은닉층의 합계값
print(a1)
z1=sigmoid(a1) #시그모이드 함수를 사용하여 출력값 계산
print(z1)

#두번째 은닉층
w2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])#가중치
b2=np.array([[0.1,0.2]]) #편향(절편)
a2=np.dot(z1,w2) + b2 #첫번째 은닉층의 합계값
print(a2)
z2=sigmoid(a2) #시그모이드 함수를 사용하여 출력값 계산
print(z2)

[[0.3 0.7 1.1]]
[[0.57444252 0.66818777 0.75026011]]
[[0.51615984 1.21402696]]
[[0.62624937 0.7710107 ]]


In [13]:
#회귀분석에서는 항등함수, 분류에서는 주로 소프트맥스 함수를 사용함
def identity_function(x): #항등함수
    return x

w3=np.array([[0.1,0.3],[0.2,0.4]])
b3=np.array([0.1,0.2])
a3=np.dot(z2,w3)+b3
print(a3)
y=identity_function(a3)
print(y)

[[0.31682708 0.69627909]]
[[0.31682708 0.69627909]]


In [ ]:
#Softmax 함수

In [15]:
#오일러 함수
print(np.exp(1))
#자연로그: 밑이 e(오일러함수)인 로그
print(np.log(1))
#상용로그: 밑이 10인로그
print(np.log10(1))
print(np.log10(10))
print(np.log10(100))

2.718281828459045
0.0
0.0
1.0
2.0


In [16]:
a=np.array([0.3,2.9,4.0])
exp_a=np.exp(a)
print(exp_a)
sum_exp_a=np.sum(exp_a) #지수함수의 합계
print(sum_exp_a)
y=exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [20]:
def softmax(a):
    exp_a=np.exp(a) #지수함수
    sum_exp_a=np.sum(exp_a) #지수함수의 합계
    y=exp_a / sum_exp_a
    return y

a=np.array([0.3, 2.9, 4.0])
print(softmax(a))
print(sum(softmax(a))) #소프트맥스의 합계는 1

#입력값이 너무 클 경우 무한대 문제가 발생함
a=np.array([1000,1100,1200])
print(softmax(a))

[0.01821127 0.24519181 0.73659691]
1.0
[nan nan nan]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [23]:
a=np.array([1010,1000,900])
print(np.exp(a))
print(np.sum(np.exp(a)))
print(np.exp(a) / np.sum(np.exp(a))) #무한대 문제가 발생

c=np.max(a) #a의 최대값
print(c)
print(a-c) #a에서의최대값을 뺀 값

#무한대 문제가 해결됨
print(np.exp(a-c)/np.sum(np.exp(a-c)))

[inf inf inf]
inf
[nan nan nan]
1010
[   0  -10 -110]
[9.99954602e-01 4.53978687e-05 1.68883521e-48]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [24]:
#무한대 문제를 해결한 softmax 함수
def softmax(a):
    c=np.max(a) #a의 최대값
    exp_a=np.exp(a-c) #a의 최대값에서 각 값을 뺀 값
    sum_exp_a=np.sum(exp_a) #지수함수의 합계값
    y=exp_a / sum_exp_a
    return y

a=np.array([0.3,2.9,4.0])
print(softmax(a))

a=np.array([1000,1100,1200])
print(softmax(a))

[0.01821127 0.24519181 0.73659691]
[1.38389653e-87 3.72007598e-44 1.00000000e+00]


In [29]:
n=[20,10,70,-50,80]
np.argmax(n) #가장 큰 값의 인덱스를 구하는 함수

4

In [28]:
a=np.array([0.3,2.9,4.0])
print(softmax(a)) #소프트맥스의 결과값은 확률
print(sum(softmax(a))) #소프트맥스의 합계는 1
idx=np.argmax(softmax(a)) #가장 큰 값의 인덱스
print(idx)
print(a[idx]) #확률이 가장 높은 값

[0.01821127 0.24519181 0.73659691]
1.0
2
4.0


### 손실함수

In [32]:
#평균제곱오차
def mean_squeared_error(y,t):
#평균제곱오차: (출력값-정답)의 제곱ㄱ의 합계 / 데이터의 갯수
#이분류의 경우 0.5를 곱하게 됨
#n class 의 경우: 1/n 을 곱함
    return 0.5 * np.sum((y-t)**2)

t=np.array([0,0,1,0,0,0,0,0,0,0])#실제값
#예측한값
y=np.array([0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0])
print(mean_squeared_error(y,t))

y=np.array([0.1,0.05,0.1,0.0,0.05,0.1,0.0,0.6,0.0,0.0])
print(mean_squeared_error(y,t))

0.09750000000000003
0.5975


In [37]:
#크로스엔트로피 오차
def cross_entropy_error(y,t):
    delta=1e-7 #무한대 또는 0이 되지 않도록 빼주는 값
    return -np.sum(t*np.log(y+delta))

In [38]:
t=np.array([0,0,1,0,0,0,0,0,0,0])#실제값
#예측한값
y=np.array([0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0])
print(cross_entropy_error(y,t))

y=np.array([0.1,0.05,0.1,0.0,0.05,0.1,0.0,0.6,0.0,0.0])
print(cross_entropy_error(y,t))

0.510825457099338
2.302584092994546
