In [1]:
help(log) # log 함수에 대한 도움말

In [2]:
log(exp(3))
log10(1e7) # = 7

x <- 10^-(1+2*1:9)
cbind(x, log(1+x), log1p(x), exp(x)-1, expm1(x))

[1] 3

[1] 7

x                                                        
 [1,] 1e-03 9.995003e-04 9.995003e-04 1.000500e-03 1.000500e-03
 [2,] 1e-05 9.999950e-06 9.999950e-06 1.000005e-05 1.000005e-05
 [3,] 1e-07 1.000000e-07 1.000000e-07 1.000000e-07 1.000000e-07
 [4,] 1e-09 1.000000e-09 1.000000e-09 1.000000e-09 1.000000e-09
 [5,] 1e-11 1.000000e-11 1.000000e-11 1.000000e-11 1.000000e-11
 [6,] 1e-13 9.992007e-14 1.000000e-13 9.992007e-14 1.000000e-13
 [7,] 1e-15 1.110223e-15 1.000000e-15 1.110223e-15 1.000000e-15
 [8,] 1e-17 0.000000e+00 1.000000e-17 0.000000e+00 1.000000e-17
 [9,] 1e-19 0.000000e+00 1.000000e-19 0.000000e+00 1.000000e-19

In [3]:
?log #도움말

In [5]:
1+2

(11+54-13)*76/9

9%%3 #나머지

5%/%2 #정수몫

5/2 #실수몫

4**2 #4의 2승

4^2 #4의 2승

4**3 #4의 3승

[1] 3

[1] 439.1111

[1] 0

[1] 2

[1] 2.5

[1] 16

[1] 16

[1] 64

In [9]:
sqrt(100) #제곱근
abs(-10) #절대값
runif(10) #0~1 사이의 난수 10개 생성
trunc(100.5) #버림
round(100.5) #반올림
round(100.567,2) #반올림, 소수 둘째자리

[1] 10

[1] 10

[1] 0.94819451 0.69808303 0.53574568 0.10162788 0.50831573 0.44549975
 [7] 0.48822304 0.20274854 0.07836856 0.50121137

[1] 100

[1] 100

[1] 100.57

In [10]:
x=5 #변수 x에 5를 대입
x # x의 값을 출력
x<-5 #대입
x
(x <-2) #대입+출력
rm(x) #x변수 출력
x<-2
y<-3
ls() #현재 사용중인 변수들
help(ls) #도움말

[1] 5

[1] 5

[1] 2

[1] "x" "y"

In [18]:
# 문자열: 작은따옴표 또는 큰따옴표로 묶음
x <- 'one'
x #print 없이 출력
print(x) #print 함수로 출력
typeof(x) #typeof(변수) 자료형
print(x,quote=F) #따옴표 제거
print(x,quote=FALSE) # F/FALSE, T/TRUE
print(x,quote=TRUE)

[1] "one"

[1] "one"


[1] "character"

[1] one
[1] one
[1] "one"


In [19]:
#서식을 이용한 출력 %s 문자열 %5.1f 전체자리수5,소수이하1자리 실수형
sprintf('%s의 키는 %5.1f이다.','김철수',170.343454)
sprintf('%s의 나이는 %i이다.','김철수',23) # %i 정수형

[1] "김철수의 키는 170.3이다."

[1] "김철수의 나이는 23이다."

In [23]:
head(iris) # 내장 데이터셋 iris의 처음 6행
tail(iris) # 마지막 6행
summary(iris) # 기초통계량

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

In [24]:
1+2 #1개의 요소를 가진 벡터
x<-c(1,2,3,4,5) #5개의 요소를 가진 벡터
x
xy<-rnorm(30) # 30개의 정규분포 난수
xy

[1] 3

[1] 1 2 3 4 5

[1] -0.24391078  0.02583637 -0.48802634  1.25262664 -2.22537637 -0.63398495
 [7] -1.51124757 -0.25879338  1.21177848  1.04165053 -1.27230561 -1.18060172
[13]  0.35544971 -0.26681177  0.03670538 -0.19860769 -1.31177848  0.54561353
[19] -0.02034427 -0.16184642  1.67238175  0.45765622  0.37256677  0.56321451
[25]  1.30255226  0.52419319  1.47034215 -0.06426402 -0.24437390  1.02775450

In [25]:
length(x) #갯수
mean(x) #평균
range(x) #범위
var(x) #분산
sd(x) #표준편차
summary(x)

[1] 5

[1] 3

[1] 1 5

[1] 2.5

[1] 1.581139

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       2       3       3       4       5 

In [26]:
x

[1] 1 2 3 4 5

In [27]:
x[1] #첫번째 값
x[2] 
x[-2] #두번째 값을 제외한 나머지
x[3] <-4
x

[1] 1

[1] 2

[1] 1 3 4 5

[1] 1 2 4 4 5

In [28]:
x<-c(3,6,9,12,15)
y<-c(5,10,15,20,25)
x
y
z<-append(x,y) #append 벡터 합치기
z

[1]  3  6  9 12 15

[1]  5 10 15 20 25

[1]  3  6  9 12 15  5 10 15 20 25

In [31]:
c(1,2)+c(4,5) #인덱스끼리 더하기
c(1,2,3)+1 #각 인덱스에 +1
v<- c(-5,-4,-3,-2,-1,0,1,2,3,4,5)
v
v <- -5:5 #-5~5
v

[1] 5 7

[1] 2 3 4

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [30]:
#sequence generation

q <- seq(from=1, to=5, by=0.5) # 1~5, 0.5씩 증가
q
qq <- seq(10) #1~10
qq

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

[1]  1  2  3  4  5  6  7  8  9 10

In [32]:
x <-c(1,2,3)
y<-c(4,2,8)
x==y #equal, 각 인덱스의 값이 같은지 비교
x!=y #not equal

[1] FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE

In [34]:
#repeat 반복, times 반복횟수
x<-rep(c('a','b','c'),times=4)
x
y<-unique(x) #중복값 제거 함수
y

[1] "a" "b" "c" "a" "b" "c" "a" "b" "c" "a" "b" "c"

[1] "a" "b" "c"

In [39]:
xx<-c('a','b','c','d','e')
xx
#xx[1]+xx[2] #문자열+문자열 => 에러
k <- paste(xx[1],xx[2]) #연결함수, 공백이 추가됨
k
k<-paste(xx[1],xx[2],sep='') #연결함수, 공백이 추가됨
k

[1] "a" "b" "c" "d" "e"

[1] "a b"

[1] "ab"

In [43]:
paste('aaa','bbb','ccc',sep=',') #문자열구분자,로 연결됨
x
paste(x,collapse='-') #문자열의 각 문자 사이에 - 삽입
paste(x,collapse=' ')
paste(x,collapse='')
substring('abcdefghijklmn',2,5) #2~5 부분문자열
paste('aaa','bbb','ccc',collapse='')

#sep 문자열 구분
#collapse 문자 각 사이

[1] "aaa,bbb,ccc"

[1] "a" "b" "c" "a" "b" "c" "a" "b" "c" "a" "b" "c"

[1] "a-b-c-a-b-c-a-b-c-a-b-c"

[1] "a b c a b c a b c a b c"

[1] "abcabcabcabc"

[1] "bcde"

[1] "aaa bbb ccc"

In [44]:
x <-runif(5) #0~1 사이의 5개의 난수
x
y<-runif(5,10,20) #10~20 사이의 5개의 난수
y
# & and 연산
(0.4 <= x) & (x<=0.7)
#0.4 <= x <= 0.7  파이썬에서만 가능
any(x>=0.9) #0.9보다 큰 값이 1개라도 있으면 TRUE
all(x<=0.9) # 모두 0.9보다 크면 TRUE
is.vector(x) #x가 벡터이면 TRUE

[1] 0.723884037 0.673039864 0.985340150 0.009673271 0.664795922

[1] 12.24886 13.44582 16.03044 12.66002 14.09201

[1] FALSE  TRUE FALSE FALSE  TRUE

[1] TRUE

[1] FALSE

[1] TRUE

In [49]:
vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec3 <- c(7,8,9)
mat1 <- rbind(vec1, vec2, vec3) # row bind 행방향 합치기
mat1
mat2 <- cbind(vec1,vec2,vec3) #column bind 열방향 합치기
mat2
colnames(mat1) <- c('A','B','C') # mat1 행렬에 필듬여 추가
mat1

[,1] [,2] [,3]
vec1 1    2    3   
vec2 4    5    6   
vec3 7    8    9

vec1 vec2 vec3
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

In [53]:
no <- c(1,2,3,4)
name <-c('apple','banana','peach','berry')
prices <-c(500,200,200,50)
qty <-c(5,2,7,9)
# 데이터프레임(2차원 형태의 테이블 구조)
fruit<-data.frame(No=no, Name=name, Price=prices, QTY=qty)
fruit
#데이터프레임[행의범위,열의범위]
fruit[1,] #1행, 모든열
fruit[,-2] #모든행, 2열 제외

No Name   Price QTY
1 1  apple  500   5  
2 2  banana 200   2  
3 3  peach  200   7  
4 4  berry   50   9

No Name  Price QTY
1 1  apple 500   5

No Price QTY
1 1  500   5  
2 2  200   2  
3 3  200   7  
4 4   50   9

In [52]:
#list
member <- list(name='김철수', address='서울',tel='010-1234-7890',pay=360)
member
member$name # key가 name인 값
member[1:3] #1,2,3 번의 key의 값
member$birth <- '1990-12-31' #새로운 key 추가
member

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-1234-7890"

$pay
[1] 360

[1] "김철수"

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-1234-7890"

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-1234-7890"

$pay
[1] 360

$birth
[1] "1990-12-31"

In [57]:
a<-array(1:12, dim=c(3,4)) #1~12, dimension 3행 4열의 2차원 배열
a 
dim(a) #배열의 차원

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 3 4

In [69]:
a<-aperm(array(1:12, dim=c(3,4))) #가로 방향으로 배열 생성
a 
dim(a) #배열의 차원

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

[1] 4 3

In [60]:
x<- array(1:6,dim=c(3,2)) # 3행 2열의 2차원 배열
x
x[1,1] # 1행 1열
x[3,2] # 3행 2열
dim(x) # 배열의 차원

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 1

[1] 6

[1] 3 2

In [68]:
#자료형 판별
class(c(1,2))
class(c(1,2,'three'))
class(matrix(c(1,2)))
class(list(c(1,2)))
class(data.frame(x=c(1,2)))
typeof(c(1,2))
typeof(c(1,2,'three'))
typeof(list(c(1,2)))

[1] "numeric"

[1] "character"

[1] "matrix"

[1] "list"

[1] "data.frame"

[1] "double"

[1] "character"

[1] "list"